[package]
name = "wikistory"
version = "0.1.0"
authors = ["beaubbe <gabriel.couvrette@gmail.com>"]

[dependencies]
reqwest = "0.7.2"
htmlstream = "0.1.2"

[[bin]]
name = "wikistory"
path = "src/wikistory.rs"
